In [ ]:
import pandas as pd

This notebook calculates and adds the average betweenness centrality (BC) to each repository for every day. BC is computed as the average BC of all stargazers contributing to the repository on that specific day. The goal is to use this enriched dataset to predict the number of new stargazers for the 31st day after a repository's creation.

In [ ]:
file_path = '/content/drive/MyDrive/PMF 2 4/STROJNO + MREZÌŒE/Projekt_v2/top_five_repos_and_its_stargazers_by_day.csv'
df = pd.read_csv(file_path)
print(df.head())

              full_name        date  stargazers_count  days_since_creation
0  AmrDeveloper/ClangQL  2024-04-05                 2                    0
1  AmrDeveloper/ClangQL  2024-04-06                22                    1
2  AmrDeveloper/ClangQL  2024-04-07                79                    2
3  AmrDeveloper/ClangQL  2024-04-08               113                    3
4  AmrDeveloper/ClangQL  2024-04-09                75                    4

##Fill missing values in date column for number of new stargazers by day

In [ ]:
missing_values = df.isna().sum()
print("NaN values per column:")
print(missing_values)

NaN values per column:
full_name               0
date                   44
stargazers_count        0
days_since_creation     0
dtype: int64

In [ ]:
for column in df.columns:
    missing_indices = df[df[column].isna()].index

    if len(missing_indices) == 0:
        continue

    print(f"Column '{column}':")
    for index in missing_indices:
        if index > 0:
            print(f"\nRow before missing value (index {index}):")
            print(df.iloc[index - 1])
        print(f"\nRow with missing value (index {index}):")
        print(df.iloc[index])
        if index < len(df) - 1:
            print(f"\nRow after missing value (index {index}):")
            print(df.iloc[index + 1])
        print("------------")

Column 'date':

Row before missing value (index 8):
full_name              AmrDeveloper/ClangQL
date                             2024-04-12
stargazers_count                          9
days_since_creation                       7
Name: 7, dtype: object

Row with missing value (index 8):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                       8
Name: 8, dtype: object

Row after missing value (index 8):
full_name              AmrDeveloper/ClangQL
date                             2024-04-14
stargazers_count                          3
days_since_creation                       9
Name: 9, dtype: object
------------

Row before missing value (index 14):
full_name              AmrDeveloper/ClangQL
date                             2024-04-18
stargazers_count                          2
days_since_creation                      13
Name: 13, dtype: object

Row with missing value (index 14):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      14
Name: 14, dtype: object

Row after missing value (index 14):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      15
Name: 15, dtype: object
------------

Row before missing value (index 15):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      14
Name: 14, dtype: object

Row with missing value (index 15):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      15
Name: 15, dtype: object

Row after missing value (index 15):
full_name              AmrDeveloper/ClangQL
date                             2024-04-21
stargazers_count                          2
days_since_creation                      16
Name: 16, dtype: object
------------

Row before missing value (index 17):
full_name              AmrDeveloper/ClangQL
date                             2024-04-21
stargazers_count                          2
days_since_creation                      16
Name: 16, dtype: object

Row with missing value (index 17):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      17
Name: 17, dtype: object

Row after missing value (index 17):
full_name              AmrDeveloper/ClangQL
date                             2024-04-23
stargazers_count                          2
days_since_creation                      18
Name: 18, dtype: object
------------

Row before missing value (index 20):
full_name              AmrDeveloper/ClangQL
date                             2024-04-24
stargazers_count                          3
days_since_creation                      19
Name: 19, dtype: object

Row with missing value (index 20):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      20
Name: 20, dtype: object

Row after missing value (index 20):
full_name              AmrDeveloper/ClangQL
date                             2024-04-26
stargazers_count                          9
days_since_creation                      21
Name: 21, dtype: object
------------

Row before missing value (index 25):
full_name              AmrDeveloper/ClangQL
date                             2024-04-29
stargazers_count                          3
days_since_creation                      24
Name: 24, dtype: object

Row with missing value (index 25):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      25
Name: 25, dtype: object

Row after missing value (index 25):
full_name              AmrDeveloper/ClangQL
date                             2024-05-01
stargazers_count                          1
days_since_creation                      26
Name: 26, dtype: object
------------

Row before missing value (index 27):
full_name              AmrDeveloper/ClangQL
date                             2024-05-01
stargazers_count                          1
days_since_creation                      26
Name: 26, dtype: object

Row with missing value (index 27):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      27
Name: 27, dtype: object

Row after missing value (index 27):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      28
Name: 28, dtype: object
------------

Row before missing value (index 28):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      27
Name: 27, dtype: object

Row with missing value (index 28):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      28
Name: 28, dtype: object

Row after missing value (index 28):
full_name              AmrDeveloper/ClangQL
date                             2024-05-04
stargazers_count                          3
days_since_creation                      29
Name: 29, dtype: object
------------

Row before missing value (index 30):
full_name              AmrDeveloper/ClangQL
date                             2024-05-04
stargazers_count                          3
days_since_creation                      29
Name: 29, dtype: object

Row with missing value (index 30):
full_name              AmrDeveloper/ClangQL
date                                    NaN
stargazers_count                          0
days_since_creation                      30
Name: 30, dtype: object

Row after missing value (index 30):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-04-15
stargazers_count                         47
days_since_creation                       0
Name: 31, dtype: object
------------

Row before missing value (index 44):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-04-27
stargazers_count                          3
days_since_creation                      12
Name: 43, dtype: object

Row with missing value (index 44):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      13
Name: 44, dtype: object

Row after missing value (index 44):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-04-29
stargazers_count                          1
days_since_creation                      14
Name: 45, dtype: object
------------

Row before missing value (index 46):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-04-29
stargazers_count                          1
days_since_creation                      14
Name: 45, dtype: object

Row with missing value (index 46):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      15
Name: 46, dtype: object

Row after missing value (index 46):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      16
Name: 47, dtype: object
------------

Row before missing value (index 47):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      15
Name: 46, dtype: object

Row with missing value (index 47):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      16
Name: 47, dtype: object

Row after missing value (index 47):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-02
stargazers_count                          1
days_since_creation                      17
Name: 48, dtype: object
------------

Row before missing value (index 49):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-02
stargazers_count                          1
days_since_creation                      17
Name: 48, dtype: object

Row with missing value (index 49):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      18
Name: 49, dtype: object

Row after missing value (index 49):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      19
Name: 50, dtype: object
------------

Row before missing value (index 50):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      18
Name: 49, dtype: object

Row with missing value (index 50):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      19
Name: 50, dtype: object

Row after missing value (index 50):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-05
stargazers_count                          1
days_since_creation                      20
Name: 51, dtype: object
------------

Row before missing value (index 52):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-05
stargazers_count                          1
days_since_creation                      20
Name: 51, dtype: object

Row with missing value (index 52):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      21
Name: 52, dtype: object

Row after missing value (index 52):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-07
stargazers_count                          1
days_since_creation                      22
Name: 53, dtype: object
------------

Row before missing value (index 56):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-09
stargazers_count                          2
days_since_creation                      24
Name: 55, dtype: object

Row with missing value (index 56):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      25
Name: 56, dtype: object

Row after missing value (index 56):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-11
stargazers_count                          1
days_since_creation                      26
Name: 57, dtype: object
------------

Row before missing value (index 58):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-11
stargazers_count                          1
days_since_creation                      26
Name: 57, dtype: object

Row with missing value (index 58):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      27
Name: 58, dtype: object

Row after missing value (index 58):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-13
stargazers_count                          2
days_since_creation                      28
Name: 59, dtype: object
------------

Row before missing value (index 61):
full_name              BenjaSOL/ore-cli-gpu
date                             2024-05-14
stargazers_count                          1
days_since_creation                      29
Name: 60, dtype: object

Row with missing value (index 61):
full_name              BenjaSOL/ore-cli-gpu
date                                    NaN
stargazers_count                          0
days_since_creation                      30
Name: 61, dtype: object

Row after missing value (index 61):
full_name              bluskript/nix-inspect
date                              2024-04-02
stargazers_count                           4
days_since_creation                        0
Name: 62, dtype: object
------------

Row before missing value (index 64):
full_name              bluskript/nix-inspect
date                              2024-04-03
stargazers_count                           3
days_since_creation                        1
Name: 63, dtype: object

Row with missing value (index 64):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        2
Name: 64, dtype: object

Row after missing value (index 64):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        3
Name: 65, dtype: object
------------

Row before missing value (index 65):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        2
Name: 64, dtype: object

Row with missing value (index 65):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        3
Name: 65, dtype: object

Row after missing value (index 65):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        4
Name: 66, dtype: object
------------

Row before missing value (index 66):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        3
Name: 65, dtype: object

Row with missing value (index 66):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        4
Name: 66, dtype: object

Row after missing value (index 66):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        5
Name: 67, dtype: object
------------

Row before missing value (index 67):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        4
Name: 66, dtype: object

Row with missing value (index 67):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        5
Name: 67, dtype: object

Row after missing value (index 67):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        6
Name: 68, dtype: object
------------

Row before missing value (index 68):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        5
Name: 67, dtype: object

Row with missing value (index 68):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        6
Name: 68, dtype: object

Row after missing value (index 68):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        7
Name: 69, dtype: object
------------

Row before missing value (index 69):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        6
Name: 68, dtype: object

Row with missing value (index 69):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                        7
Name: 69, dtype: object

Row after missing value (index 69):
full_name              bluskript/nix-inspect
date                              2024-04-10
stargazers_count                           1
days_since_creation                        8
Name: 70, dtype: object
------------

Row before missing value (index 86):
full_name              bluskript/nix-inspect
date                              2024-04-25
stargazers_count                           1
days_since_creation                       23
Name: 85, dtype: object

Row with missing value (index 86):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                       24
Name: 86, dtype: object

Row after missing value (index 86):
full_name              bluskript/nix-inspect
date                              2024-04-27
stargazers_count                           1
days_since_creation                       25
Name: 87, dtype: object
------------

Row before missing value (index 89):
full_name              bluskript/nix-inspect
date                              2024-04-28
stargazers_count                           3
days_since_creation                       26
Name: 88, dtype: object

Row with missing value (index 89):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                       27
Name: 89, dtype: object

Row after missing value (index 89):
full_name              bluskript/nix-inspect
date                              2024-04-30
stargazers_count                           2
days_since_creation                       28
Name: 90, dtype: object
------------

Row before missing value (index 91):
full_name              bluskript/nix-inspect
date                              2024-04-30
stargazers_count                           2
days_since_creation                       28
Name: 90, dtype: object

Row with missing value (index 91):
full_name              bluskript/nix-inspect
date                                     NaN
stargazers_count                           0
days_since_creation                       29
Name: 91, dtype: object

Row after missing value (index 91):
full_name              bluskript/nix-inspect
date                              2024-05-02
stargazers_count                           3
days_since_creation                       30
Name: 92, dtype: object
------------

Row before missing value (index 102):
full_name              tonyke-bot/ore-miner
date                             2024-04-21
stargazers_count                          1
days_since_creation                       8
Name: 101, dtype: object

Row with missing value (index 102):
full_name              tonyke-bot/ore-miner

In [ ]:
df.at[8, 'date'] = '2024-04-13'
print(df.iloc[8])

df.at[14, 'date'] = '2024-04-19'
print(df.iloc[14])

df.at[15, 'date'] = '2024-04-20'
print(df.iloc[15])

df.at[17, 'date'] = '2024-04-22'
print(df.iloc[17])

df.at[20, 'date'] = '2024-04-25'
print(df.iloc[20])

df.at[25, 'date'] = '2024-04-30'
print(df.iloc[25])

full_name              AmrDeveloper/ClangQL
date                             2024-04-13
stargazers_count                          0
days_since_creation                       8
Name: 8, dtype: object
full_name              AmrDeveloper/ClangQL
date                             2024-04-19
stargazers_count                          0
days_since_creation                      14
Name: 14, dtype: object
full_name              AmrDeveloper/ClangQL
date                             2024-04-20
stargazers_count                          0
days_since_creation                      15
Name: 15, dtype: object
full_name              AmrDeveloper/ClangQL
date                             2024-04-22
stargazers_count                          0
days_since_creation                      17
Name: 17, dtype: object
full_name              AmrDeveloper/ClangQL
date                             2024-04-25
stargazers_count                          0
days_since_creation                      20
Name: 20, dtype: object
full_name              AmrDeveloper/ClangQL
date                             2024-04-30
stargazers_count                          0
days_since_creation                      25
Name: 25, dtype: object

In [ ]:
missing_values_date = df[df['date'].isna()]
print(missing_values_date)

                 full_name date  stargazers_count  days_since_creation
27    AmrDeveloper/ClangQL  NaN                 0                   27
28    AmrDeveloper/ClangQL  NaN                 0                   28
30    AmrDeveloper/ClangQL  NaN                 0                   30
44    BenjaSOL/ore-cli-gpu  NaN                 0                   13
46    BenjaSOL/ore-cli-gpu  NaN                 0                   15
47    BenjaSOL/ore-cli-gpu  NaN                 0                   16
49    BenjaSOL/ore-cli-gpu  NaN                 0                   18
50    BenjaSOL/ore-cli-gpu  NaN                 0                   19
52    BenjaSOL/ore-cli-gpu  NaN                 0                   21
56    BenjaSOL/ore-cli-gpu  NaN                 0                   25
58    BenjaSOL/ore-cli-gpu  NaN                 0                   27
61    BenjaSOL/ore-cli-gpu  NaN                 0                   30
64   bluskript/nix-inspect  NaN                 0                    2
65   bluskript/nix-inspect  NaN                 0                    3
66   bluskript/nix-inspect  NaN                 0                    4
67   bluskript/nix-inspect  NaN                 0                    5
68   bluskript/nix-inspect  NaN                 0                    6
69   bluskript/nix-inspect  NaN                 0                    7
86   bluskript/nix-inspect  NaN                 0                   24
89   bluskript/nix-inspect  NaN                 0                   27
91   bluskript/nix-inspect  NaN                 0                   29
102   tonyke-bot/ore-miner  NaN                 0                    9
104   tonyke-bot/ore-miner  NaN                 0                   11
105   tonyke-bot/ore-miner  NaN                 0                   12
106   tonyke-bot/ore-miner  NaN                 0                   13
107   tonyke-bot/ore-miner  NaN                 0                   14
109   tonyke-bot/ore-miner  NaN                 0                   16
110   tonyke-bot/ore-miner  NaN                 0                   17
111   tonyke-bot/ore-miner  NaN                 0                   18
112   tonyke-bot/ore-miner  NaN                 0                   19
113   tonyke-bot/ore-miner  NaN                 0                   20
114   tonyke-bot/ore-miner  NaN                 0                   21
116   tonyke-bot/ore-miner  NaN                 0                   23
118   tonyke-bot/ore-miner  NaN                 0                   25
119   tonyke-bot/ore-miner  NaN                 0                   26
121   tonyke-bot/ore-miner  NaN                 0                   28
122   tonyke-bot/ore-miner  NaN                 0                   29
123   tonyke-bot/ore-miner  NaN                 0                   30

In [ ]:
df.head(30)

               full_name        date  stargazers_count  days_since_creation
0   AmrDeveloper/ClangQL  2024-04-05                 2                    0
1   AmrDeveloper/ClangQL  2024-04-06                22                    1
2   AmrDeveloper/ClangQL  2024-04-07                79                    2
3   AmrDeveloper/ClangQL  2024-04-08               113                    3
4   AmrDeveloper/ClangQL  2024-04-09                75                    4
5   AmrDeveloper/ClangQL  2024-04-10                54                    5
6   AmrDeveloper/ClangQL  2024-04-11                21                    6
7   AmrDeveloper/ClangQL  2024-04-12                 9                    7
8   AmrDeveloper/ClangQL  2024-04-13                 0                    8
9   AmrDeveloper/ClangQL  2024-04-14                 3                    9
10  AmrDeveloper/ClangQL  2024-04-15                 2                   10
11  AmrDeveloper/ClangQL  2024-04-16                 4                   11
12  AmrDeveloper/ClangQL  2024-04-17                 1                   12
13  AmrDeveloper/ClangQL  2024-04-18                 2                   13
14  AmrDeveloper/ClangQL  2024-04-19                 0                   14
15  AmrDeveloper/ClangQL  2024-04-20                 0                   15
16  AmrDeveloper/ClangQL  2024-04-21                 2                   16
17  AmrDeveloper/ClangQL  2024-04-22                 0                   17
18  AmrDeveloper/ClangQL  2024-04-23                 2                   18
19  AmrDeveloper/ClangQL  2024-04-24                 3                   19
20  AmrDeveloper/ClangQL  2024-04-25                 0                   20
21  AmrDeveloper/ClangQL  2024-04-26                 9                   21
22  AmrDeveloper/ClangQL  2024-04-27                10                   22
23  AmrDeveloper/ClangQL  2024-04-28                 1                   23
24  AmrDeveloper/ClangQL  2024-04-29                 3                   24
25  AmrDeveloper/ClangQL  2024-04-30                 0                   25
26  AmrDeveloper/ClangQL  2024-05-01                 1                   26
27  AmrDeveloper/ClangQL         NaN                 0                   27
28  AmrDeveloper/ClangQL         NaN                 0                   28
29  AmrDeveloper/ClangQL  2024-05-04                 3                   29

In [ ]:
df.at[27, 'date'] = '2024-05-02'
print(df.iloc[27])

df.at[28, 'date'] = '2024-05-03'
print(df.iloc[28])
print(df.iloc[29])

full_name              AmrDeveloper/ClangQL
date                             2024-05-02
stargazers_count                          0
days_since_creation                      27
Name: 27, dtype: object
full_name              AmrDeveloper/ClangQL
date                             2024-05-03
stargazers_count                          0
days_since_creation                      28
Name: 28, dtype: object
full_name              AmrDeveloper/ClangQL
date                             2024-05-04
stargazers_count                          3
days_since_creation                      29
Name: 29, dtype: object

In [ ]:
print(df.iloc[30:61])

               full_name        date  stargazers_count  days_since_creation
30  AmrDeveloper/ClangQL         NaN                 0                   30
31  BenjaSOL/ore-cli-gpu  2024-04-15                47                    0
32  BenjaSOL/ore-cli-gpu  2024-04-16                20                    1
33  BenjaSOL/ore-cli-gpu  2024-04-17                54                    2
34  BenjaSOL/ore-cli-gpu  2024-04-18                68                    3
35  BenjaSOL/ore-cli-gpu  2024-04-19                 8                    4
36  BenjaSOL/ore-cli-gpu  2024-04-20                 6                    5
37  BenjaSOL/ore-cli-gpu  2024-04-21                 8                    6
38  BenjaSOL/ore-cli-gpu  2024-04-22                 2                    7
39  BenjaSOL/ore-cli-gpu  2024-04-23                 1                    8
40  BenjaSOL/ore-cli-gpu  2024-04-24                 1                    9
41  BenjaSOL/ore-cli-gpu  2024-04-25                 1                   10
42  BenjaSOL/ore-cli-gpu  2024-04-26                 2                   11
43  BenjaSOL/ore-cli-gpu  2024-04-27                 3                   12
44  BenjaSOL/ore-cli-gpu         NaN                 0                   13
45  BenjaSOL/ore-cli-gpu  2024-04-29                 1                   14
46  BenjaSOL/ore-cli-gpu         NaN                 0                   15
47  BenjaSOL/ore-cli-gpu         NaN                 0                   16
48  BenjaSOL/ore-cli-gpu  2024-05-02                 1                   17
49  BenjaSOL/ore-cli-gpu         NaN                 0                   18
50  BenjaSOL/ore-cli-gpu         NaN                 0                   19
51  BenjaSOL/ore-cli-gpu  2024-05-05                 1                   20
52  BenjaSOL/ore-cli-gpu         NaN                 0                   21
53  BenjaSOL/ore-cli-gpu  2024-05-07                 1                   22
54  BenjaSOL/ore-cli-gpu  2024-05-08                 1                   23
55  BenjaSOL/ore-cli-gpu  2024-05-09                 2                   24
56  BenjaSOL/ore-cli-gpu         NaN                 0                   25
57  BenjaSOL/ore-cli-gpu  2024-05-11                 1                   26
58  BenjaSOL/ore-cli-gpu         NaN                 0                   27
59  BenjaSOL/ore-cli-gpu  2024-05-13                 2                   28
60  BenjaSOL/ore-cli-gpu  2024-05-14                 1                   29

In [ ]:
df.at[30, 'date'] = '2024-05-05'
df.at[44, 'date'] = '2024-04-28'
df.at[46, 'date'] = '2024-04-30'
df.at[47, 'date'] = '2024-05-01'
df.at[49, 'date'] = '2024-05-03'
df.at[50, 'date'] = '2024-05-04'
df.at[52, 'date'] = '2024-05-06'
df.at[56, 'date'] = '2024-05-10'
df.at[58, 'date'] = '2024-05-12'

In [ ]:
print(df.iloc[60:91])

                full_name        date  stargazers_count  days_since_creation
60   BenjaSOL/ore-cli-gpu  2024-05-14                 1                   29
61   BenjaSOL/ore-cli-gpu         NaN                 0                   30
62  bluskript/nix-inspect  2024-04-02                 4                    0
63  bluskript/nix-inspect  2024-04-03                 3                    1
64  bluskript/nix-inspect         NaN                 0                    2
65  bluskript/nix-inspect         NaN                 0                    3
66  bluskript/nix-inspect         NaN                 0                    4
67  bluskript/nix-inspect         NaN                 0                    5
68  bluskript/nix-inspect         NaN                 0                    6
69  bluskript/nix-inspect         NaN                 0                    7
70  bluskript/nix-inspect  2024-04-10                 1                    8
71  bluskript/nix-inspect  2024-04-11                68                    9
72  bluskript/nix-inspect  2024-04-12                35                   10
73  bluskript/nix-inspect  2024-04-13                 6                   11
74  bluskript/nix-inspect  2024-04-14                 7                   12
75  bluskript/nix-inspect  2024-04-15                19                   13
76  bluskript/nix-inspect  2024-04-16                40                   14
77  bluskript/nix-inspect  2024-04-17                13                   15
78  bluskript/nix-inspect  2024-04-18                 6                   16
79  bluskript/nix-inspect  2024-04-19                 4                   17
80  bluskript/nix-inspect  2024-04-20                 3                   18
81  bluskript/nix-inspect  2024-04-21                 1                   19
82  bluskript/nix-inspect  2024-04-22                 1                   20
83  bluskript/nix-inspect  2024-04-23                 4                   21
84  bluskript/nix-inspect  2024-04-24                 2                   22
85  bluskript/nix-inspect  2024-04-25                 1                   23
86  bluskript/nix-inspect         NaN                 0                   24
87  bluskript/nix-inspect  2024-04-27                 1                   25
88  bluskript/nix-inspect  2024-04-28                 3                   26
89  bluskript/nix-inspect         NaN                 0                   27
90  bluskript/nix-inspect  2024-04-30                 2                   28

In [ ]:
df.at[61, 'date'] = '2024-05-15'
df.at[64, 'date'] = '2024-04-04'
df.at[65, 'date'] = '2024-04-05'
df.at[66, 'date'] = '2024-04-06'
df.at[67, 'date'] = '2024-04-07'
df.at[68, 'date'] = '2024-04-08'
df.at[69, 'date'] = '2024-04-09'
df.at[86, 'date'] = '2024-04-26'
df.at[89, 'date'] = '2024-04-29'

In [ ]:
print(df.iloc[90:120])

                 full_name        date  stargazers_count  days_since_creation
90   bluskript/nix-inspect  2024-04-30                 2                   28
91   bluskript/nix-inspect         NaN                 0                   29
92   bluskript/nix-inspect  2024-05-02                 3                   30
93    tonyke-bot/ore-miner  2024-04-13                70                    0
94    tonyke-bot/ore-miner  2024-04-14               115                    1
95    tonyke-bot/ore-miner  2024-04-15                63                    2
96    tonyke-bot/ore-miner  2024-04-16               110                    3
97    tonyke-bot/ore-miner  2024-04-17                72                    4
98    tonyke-bot/ore-miner  2024-04-18                26                    5
99    tonyke-bot/ore-miner  2024-04-19                 7                    6
100   tonyke-bot/ore-miner  2024-04-20                 1                    7
101   tonyke-bot/ore-miner  2024-04-21                 1                    8
102   tonyke-bot/ore-miner         NaN                 0                    9
103   tonyke-bot/ore-miner  2024-04-23                 2                   10
104   tonyke-bot/ore-miner         NaN                 0                   11
105   tonyke-bot/ore-miner         NaN                 0                   12
106   tonyke-bot/ore-miner         NaN                 0                   13
107   tonyke-bot/ore-miner         NaN                 0                   14
108   tonyke-bot/ore-miner  2024-04-28                 1                   15
109   tonyke-bot/ore-miner         NaN                 0                   16
110   tonyke-bot/ore-miner         NaN                 0                   17
111   tonyke-bot/ore-miner         NaN                 0                   18
112   tonyke-bot/ore-miner         NaN                 0                   19
113   tonyke-bot/ore-miner         NaN                 0                   20
114   tonyke-bot/ore-miner         NaN                 0                   21
115   tonyke-bot/ore-miner  2024-05-05                 2                   22
116   tonyke-bot/ore-miner         NaN                 0                   23
117   tonyke-bot/ore-miner  2024-05-07                 1                   24
118   tonyke-bot/ore-miner         NaN                 0                   25
119   tonyke-bot/ore-miner         NaN                 0                   26

In [ ]:
df.at[91, 'date'] = '2024-05-01'
df.at[102, 'date'] = '2024-04-22'
df.at[104, 'date'] = '2024-04-24'
df.at[105, 'date'] = '2024-04-25'
df.at[106, 'date'] = '2024-04-26'
df.at[107, 'date'] = '2024-04-27'
df.at[109, 'date'] = '2024-04-29'
df.at[110, 'date'] = '2024-05-30'
df.at[111, 'date'] = '2024-05-01'
df.at[112, 'date'] = '2024-05-02'
df.at[113, 'date'] = '2024-05-03'
df.at[114, 'date'] = '2024-05-04'
df.at[116, 'date'] = '2024-05-06'
df.at[118, 'date'] = '2024-05-08'
df.at[119, 'date'] = '2024-05-09'

In [ ]:
df.at[121, 'date'] = '2024-05-11'
df.at[122, 'date'] = '2024-05-12'
df.at[123, 'date'] = '2024-05-13'

In [ ]:
missing_values = df.isna().sum()
print("NaN values per column:")
print(missing_values)

NaN values per column:
full_name              0
date                   0
stargazers_count       0
days_since_creation    0
dtype: int64

In [ ]:
df.head()

              full_name        date  stargazers_count  days_since_creation
0  AmrDeveloper/ClangQL  2024-04-05                 2                    0
1  AmrDeveloper/ClangQL  2024-04-06                22                    1
2  AmrDeveloper/ClangQL  2024-04-07                79                    2
3  AmrDeveloper/ClangQL  2024-04-08               113                    3
4  AmrDeveloper/ClangQL  2024-04-09                75                    4

##Remove missing values from files with BC for each stargazer

In [ ]:
import pandas as pd

In [ ]:
file_path = '/content/drive/MyDrive/PMF 2 4/STROJNO + MREZÌŒE/Projekt_v2/stargazers_with_betweenness_AmrDeveloper_ClangQL.csv'
ClangQL_df = pd.read_csv(file_path)
print(ClangQL_df.head())

  stargazer_login          Node  Betweenness Centrality
0    markoeltiger  markoeltiger                     0.0
1         mhewedy       mhewedy                     0.0
2     WasistJonas   WasistJonas                     0.0
3       theashraf     theashraf                     0.0
4      sleepy-cat    sleepy-cat                     0.0

In [ ]:
print(ClangQL_df.isna().sum())

stargazer_login            0
Node                      24
Betweenness Centrality    24
dtype: int64

In [ ]:
ClangQL_df_cleaned = ClangQL_df.dropna()
print(ClangQL_df_cleaned.isna().sum())

stargazer_login           0
Node                      0
Betweenness Centrality    0
dtype: int64

In [ ]:
file_path = '/content/drive/MyDrive/PMF 2 4/STROJNO + MREZÌŒE/Projekt_v2/stargazers_with_betweenness_BenjaSOL_ore-cli-gpu.csv'
ore_df = pd.read_csv(file_path)
print(ore_df.head())

  stargazer_login         Node  Betweenness Centrality
0        BenjaSOL     BenjaSOL                0.000000
1          nfanet       nfanet                0.000281
2        tarvos21     tarvos21                0.000184
3       edwinosky    edwinosky                0.000000
4     Tofu-killer  Tofu-killer                0.000000

In [ ]:
print(ore_df.isna().sum())

stargazer_login           0
Node                      8
Betweenness Centrality    8
dtype: int64

In [ ]:
ore_df_cleaned = ore_df.dropna()
print(ore_df_cleaned.isna().sum())

stargazer_login           0
Node                      0
Betweenness Centrality    0
dtype: int64

In [ ]:
file_path = '/content/drive/MyDrive/PMF 2 4/STROJNO + MREZÌŒE/Projekt_v2/stargazers_with_betweenness_bluskript_nix-inspect.csv'
nix_df = pd.read_csv(file_path)
print(nix_df.head())

  stargazer_login       Node  Betweenness Centrality
0         SEAPUNK    SEAPUNK                     0.0
1       bluskript  bluskript                     0.0
2         Jappie3    Jappie3                     0.0
3        yusdacra   yusdacra                     0.0
4          terlar     terlar                     0.0

In [ ]:
print(nix_df.isna().sum())

stargazer_login            0
Node                      21
Betweenness Centrality    21
dtype: int64

In [ ]:
nix_df_cleaned = nix_df.dropna()
print(nix_df_cleaned.isna().sum())

stargazer_login           0
Node                      0
Betweenness Centrality    0
dtype: int64

In [ ]:
file_path = '/content/drive/MyDrive/PMF 2 4/STROJNO + MREZÌŒE/Projekt_v2/stargazers_with_betweenness_tonyke-bot_ore-miner.csv'
miner_df = pd.read_csv(file_path)
print(miner_df.head())

  stargazer_login          Node  Betweenness Centrality
0        tommy-ca      tommy-ca                0.000281
1       Brucecarl     Brucecarl                0.000093
2            iczc          iczc                0.000000
3        okeyzero      okeyzero                0.000184
4    xiaoduzi1919  xiaoduzi1919                0.000000

In [ ]:
print(miner_df.isna().sum())

stargazer_login           0
Node                      8
Betweenness Centrality    8
dtype: int64

In [ ]:
miner_df_cleaned = miner_df.dropna()
print(miner_df_cleaned.isna().sum())

stargazer_login           0
Node                      0
Betweenness Centrality    0
dtype: int64

In [ ]:
file_path = '/content/drive/MyDrive/PMF 2 4/STROJNO + MREZÌŒE/Projekt_v2/stargazers_with_betweenness_tsoding_good_training_language.csv'
good_df = pd.read_csv(file_path)
print(good_df.head())

  stargazer_login       Node  Betweenness Centrality
0           rexim      rexim                     0.0
1         Melidee    Melidee                     0.0
2        REgorion   REgorion                     0.0
3       Pixelsuft  Pixelsuft                     0.0
4         9ziggy9    9ziggy9                     0.0

In [ ]:
print(good_df.isna().sum())

stargazer_login            0
Node                      60
Betweenness Centrality    60
dtype: int64

In [ ]:
good_df_cleaned = good_df.dropna()
print(good_df_cleaned.isna().sum())

stargazer_login           0
Node                      0
Betweenness Centrality    0
dtype: int64

#Add average BC for each day

In [ ]:
df.head(31)

               full_name        date  stargazers_count  days_since_creation
0   AmrDeveloper/ClangQL  2024-04-05                 2                    0
1   AmrDeveloper/ClangQL  2024-04-06                22                    1
2   AmrDeveloper/ClangQL  2024-04-07                79                    2
3   AmrDeveloper/ClangQL  2024-04-08               113                    3
4   AmrDeveloper/ClangQL  2024-04-09                75                    4
5   AmrDeveloper/ClangQL  2024-04-10                54                    5
6   AmrDeveloper/ClangQL  2024-04-11                21                    6
7   AmrDeveloper/ClangQL  2024-04-12                 9                    7
8   AmrDeveloper/ClangQL  2024-04-13                 0                    8
9   AmrDeveloper/ClangQL  2024-04-14                 3                    9
10  AmrDeveloper/ClangQL  2024-04-15                 2                   10
11  AmrDeveloper/ClangQL  2024-04-16                 4                   11
12  AmrDeveloper/ClangQL  2024-04-17                 1                   12
13  AmrDeveloper/ClangQL  2024-04-18                 2                   13
14  AmrDeveloper/ClangQL  2024-04-19                 0                   14
15  AmrDeveloper/ClangQL  2024-04-20                 0                   15
16  AmrDeveloper/ClangQL  2024-04-21                 2                   16
17  AmrDeveloper/ClangQL  2024-04-22                 0                   17
18  AmrDeveloper/ClangQL  2024-04-23                 2                   18
19  AmrDeveloper/ClangQL  2024-04-24                 3                   19
20  AmrDeveloper/ClangQL  2024-04-25                 0                   20
21  AmrDeveloper/ClangQL  2024-04-26                 9                   21
22  AmrDeveloper/ClangQL  2024-04-27                10                   22
23  AmrDeveloper/ClangQL  2024-04-28                 1                   23
24  AmrDeveloper/ClangQL  2024-04-29                 3                   24
25  AmrDeveloper/ClangQL  2024-04-30                 0                   25
26  AmrDeveloper/ClangQL  2024-05-01                 1                   26
27  AmrDeveloper/ClangQL  2024-05-02                 0                   27
28  AmrDeveloper/ClangQL  2024-05-03                 0                   28
29  AmrDeveloper/ClangQL  2024-05-04                 3                   29
30  AmrDeveloper/ClangQL  2024-05-05                 0                   30

In [ ]:
ClangQL_df_cleaned.head(30)

        stargazer_login                 Node  Betweenness Centrality
0          markoeltiger         markoeltiger                0.000000
1               mhewedy              mhewedy                0.000000
2           WasistJonas          WasistJonas                0.000000
3             theashraf            theashraf                0.000000
4            sleepy-cat           sleepy-cat                0.000000
5               kehoecj              kehoecj                0.022829
6                danien               danien                0.000000
7            John-Titor           John-Titor                0.000000
8   KlausEverWalkingDev  KlausEverWalkingDev                0.000000
9              lgastako             lgastako                0.000000
10          alvarhansen          alvarhansen                0.000000
11            patrickmn            patrickmn                0.000000
12                tlemo                tlemo                0.000000
13           jtpedersen           jtpedersen                0.000000
14            jimmyrcom            jimmyrcom                0.006333
15                 gusc                 gusc                0.000000
16               DomCie               DomCie                0.000000
17             AaronC81             AaronC81                0.000000
18          MattBolitho          MattBolitho                0.000000
19            codeinred            codeinred                0.000000
20            flounderK            flounderK                0.000000
21             Cons-Cat             Cons-Cat                0.000000
22         SivkovSavely         SivkovSavely                0.000000
23      b-tapia-morales      b-tapia-morales                0.000000
24               PMeira               PMeira                0.000000
25          dufferzafar          dufferzafar                0.000000
26        jeffreysblake        jeffreysblake                0.000000
27         MahmoudFayed         MahmoudFayed                0.000000
28                f8ith                f8ith                0.000000
29            JCWasmx86            JCWasmx86                0.000000

In [ ]:
def calculate_average_bc(df, stargazers_df):
    average_bc = []
    start_idx = 0

    for i, row in df.iterrows():
        num_stargazers = row['stargazers_count']
        end_idx = start_idx + num_stargazers

        if end_idx <= len(stargazers_df):
            avg_bc = stargazers_df['Betweenness Centrality'].iloc[start_idx:end_idx].mean()
            average_bc.append(avg_bc)
        else:
            average_bc.append(None)

        start_idx = end_idx

    return average_bc

In [ ]:
repo_name = 'AmrDeveloper/ClangQL'
repo_df = df[df['full_name'] == repo_name].reset_index(drop=True)
repo_df['average_bc'] = calculate_average_bc(repo_df, ClangQL_df_cleaned)

print(repo_df)

               full_name        date  stargazers_count  days_since_creation  \
0   AmrDeveloper/ClangQL  2024-04-05                 2                    0
1   AmrDeveloper/ClangQL  2024-04-06                22                    1
2   AmrDeveloper/ClangQL  2024-04-07                79                    2
3   AmrDeveloper/ClangQL  2024-04-08               113                    3
4   AmrDeveloper/ClangQL  2024-04-09                75                    4
5   AmrDeveloper/ClangQL  2024-04-10                54                    5
6   AmrDeveloper/ClangQL  2024-04-11                21                    6
7   AmrDeveloper/ClangQL  2024-04-12                 9                    7
8   AmrDeveloper/ClangQL  2024-04-13                 0                    8
9   AmrDeveloper/ClangQL  2024-04-14                 3                    9
10  AmrDeveloper/ClangQL  2024-04-15                 2                   10
11  AmrDeveloper/ClangQL  2024-04-16                 4                   11
12  AmrDeveloper/ClangQL  2024-04-17                 1                   12
13  AmrDeveloper/ClangQL  2024-04-18                 2                   13
14  AmrDeveloper/ClangQL  2024-04-19                 0                   14
15  AmrDeveloper/ClangQL  2024-04-20                 0                   15
16  AmrDeveloper/ClangQL  2024-04-21                 2                   16
17  AmrDeveloper/ClangQL  2024-04-22                 0                   17
18  AmrDeveloper/ClangQL  2024-04-23                 2                   18
19  AmrDeveloper/ClangQL  2024-04-24                 3                   19
20  AmrDeveloper/ClangQL  2024-04-25                 0                   20
21  AmrDeveloper/ClangQL  2024-04-26                 9                   21
22  AmrDeveloper/ClangQL  2024-04-27                10                   22
23  AmrDeveloper/ClangQL  2024-04-28                 1                   23
24  AmrDeveloper/ClangQL  2024-04-29                 3                   24
25  AmrDeveloper/ClangQL  2024-04-30                 0                   25
26  AmrDeveloper/ClangQL  2024-05-01                 1                   26
27  AmrDeveloper/ClangQL  2024-05-02                 0                   27
28  AmrDeveloper/ClangQL  2024-05-03                 0                   28
29  AmrDeveloper/ClangQL  2024-05-04                 3                   29
30  AmrDeveloper/ClangQL  2024-05-05                 0                   30

    average_bc
0     0.000000
1     0.001326
2     0.001998
3     0.000545
4     0.002579
5     0.000598
6     0.003750
7     0.000585
8          NaN
9     0.000000
10    0.000000
11    0.000000
12    0.000000
13    0.000000
14         NaN
15         NaN
16    0.000000
17         NaN
18    0.007523
19    0.001921
20         NaN
21    0.000000
22    0.000507
23    0.037648
24    0.000000
25         NaN
26    0.000000
27         NaN
28         NaN
29    0.000000
30         NaN

In [ ]:
print(repo_df.isna().sum())
repo_df['average_bc'] = repo_df['average_bc'].fillna(0)
print(repo_df.isna().sum())

full_name              0
date                   0
stargazers_count       0
days_since_creation    0
average_bc             9
dtype: int64
full_name              0
date                   0
stargazers_count       0
days_since_creation    0
average_bc             0
dtype: int64

In [ ]:
def process_repo(repo_name, stargazers_df):
    repo_df = df[df['full_name'] == repo_name].reset_index(drop=True)
    repo_df['average_bc'] = calculate_average_bc(repo_df, stargazers_df)
    return repo_df

processed_ore_cli_gpu_df = process_repo('BenjaSOL/ore-cli-gpu', ore_df_cleaned)
print(processed_ore_cli_gpu_df)

               full_name        date  stargazers_count  days_since_creation  \
0   BenjaSOL/ore-cli-gpu  2024-04-15                47                    0
1   BenjaSOL/ore-cli-gpu  2024-04-16                20                    1
2   BenjaSOL/ore-cli-gpu  2024-04-17                54                    2
3   BenjaSOL/ore-cli-gpu  2024-04-18                68                    3
4   BenjaSOL/ore-cli-gpu  2024-04-19                 8                    4
5   BenjaSOL/ore-cli-gpu  2024-04-20                 6                    5
6   BenjaSOL/ore-cli-gpu  2024-04-21                 8                    6
7   BenjaSOL/ore-cli-gpu  2024-04-22                 2                    7
8   BenjaSOL/ore-cli-gpu  2024-04-23                 1                    8
9   BenjaSOL/ore-cli-gpu  2024-04-24                 1                    9
10  BenjaSOL/ore-cli-gpu  2024-04-25                 1                   10
11  BenjaSOL/ore-cli-gpu  2024-04-26                 2                   11
12  BenjaSOL/ore-cli-gpu  2024-04-27                 3                   12
13  BenjaSOL/ore-cli-gpu  2024-04-28                 0                   13
14  BenjaSOL/ore-cli-gpu  2024-04-29                 1                   14
15  BenjaSOL/ore-cli-gpu  2024-04-30                 0                   15
16  BenjaSOL/ore-cli-gpu  2024-05-01                 0                   16
17  BenjaSOL/ore-cli-gpu  2024-05-02                 1                   17
18  BenjaSOL/ore-cli-gpu  2024-05-03                 0                   18
19  BenjaSOL/ore-cli-gpu  2024-05-04                 0                   19
20  BenjaSOL/ore-cli-gpu  2024-05-05                 1                   20
21  BenjaSOL/ore-cli-gpu  2024-05-06                 0                   21
22  BenjaSOL/ore-cli-gpu  2024-05-07                 1                   22
23  BenjaSOL/ore-cli-gpu  2024-05-08                 1                   23
24  BenjaSOL/ore-cli-gpu  2024-05-09                 2                   24
25  BenjaSOL/ore-cli-gpu  2024-05-10                 0                   25
26  BenjaSOL/ore-cli-gpu  2024-05-11                 1                   26
27  BenjaSOL/ore-cli-gpu  2024-05-12                 0                   27
28  BenjaSOL/ore-cli-gpu  2024-05-13                 2                   28
29  BenjaSOL/ore-cli-gpu  2024-05-14                 1                   29
30  BenjaSOL/ore-cli-gpu  2024-05-15                 0                   30

    average_bc
0     0.000139
1     0.000090
2     0.004143
3     0.000086
4     0.000023
5     0.000061
6     0.000046
7     0.000342
8     0.000000
9     0.000000
10    0.000000
11    0.000092
12    0.000061
13         NaN
14    0.000184
15         NaN
16         NaN
17    0.002224
18         NaN
19         NaN
20    0.000000
21         NaN
22    0.000000
23         NaN
24         NaN
25         NaN
26         NaN
27         NaN
28         NaN
29         NaN
30         NaN

In [ ]:
print(processed_ore_cli_gpu_df.isna().sum())
processed_ore_cli_gpu_df['average_bc'] = processed_ore_cli_gpu_df['average_bc'].fillna(0)
print(processed_ore_cli_gpu_df.isna().sum())

full_name               0
date                    0
stargazers_count        0
days_since_creation     0
average_bc             14
dtype: int64
full_name              0
date                   0
stargazers_count       0
days_since_creation    0
average_bc             0
dtype: int64

In [ ]:
processed_nix_inspect_df = process_repo('bluskript/nix-inspect', nix_df_cleaned)
print(processed_nix_inspect_df)

                full_name        date  stargazers_count  days_since_creation  \
0   bluskript/nix-inspect  2024-04-02                 4                    0
1   bluskript/nix-inspect  2024-04-03                 3                    1
2   bluskript/nix-inspect  2024-04-04                 0                    2
3   bluskript/nix-inspect  2024-04-05                 0                    3
4   bluskript/nix-inspect  2024-04-06                 0                    4
5   bluskript/nix-inspect  2024-04-07                 0                    5
6   bluskript/nix-inspect  2024-04-08                 0                    6
7   bluskript/nix-inspect  2024-04-09                 0                    7
8   bluskript/nix-inspect  2024-04-10                 1                    8
9   bluskript/nix-inspect  2024-04-11                68                    9
10  bluskript/nix-inspect  2024-04-12                35                   10
11  bluskript/nix-inspect  2024-04-13                 6                   11
12  bluskript/nix-inspect  2024-04-14                 7                   12
13  bluskript/nix-inspect  2024-04-15                19                   13
14  bluskript/nix-inspect  2024-04-16                40                   14
15  bluskript/nix-inspect  2024-04-17                13                   15
16  bluskript/nix-inspect  2024-04-18                 6                   16
17  bluskript/nix-inspect  2024-04-19                 4                   17
18  bluskript/nix-inspect  2024-04-20                 3                   18
19  bluskript/nix-inspect  2024-04-21                 1                   19
20  bluskript/nix-inspect  2024-04-22                 1                   20
21  bluskript/nix-inspect  2024-04-23                 4                   21
22  bluskript/nix-inspect  2024-04-24                 2                   22
23  bluskript/nix-inspect  2024-04-25                 1                   23
24  bluskript/nix-inspect  2024-04-26                 0                   24
25  bluskript/nix-inspect  2024-04-27                 1                   25
26  bluskript/nix-inspect  2024-04-28                 3                   26
27  bluskript/nix-inspect  2024-04-29                 0                   27
28  bluskript/nix-inspect  2024-04-30                 2                   28
29  bluskript/nix-inspect  2024-05-01                 0                   29
30  bluskript/nix-inspect  2024-05-02                 3                   30

    average_bc
0     0.000000
1     0.000000
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8     0.000000
9     0.000188
10    0.000823
11    0.000000
12    0.000000
13    0.004321
14    0.000157
15    0.000761
16    0.000000
17    0.000000
18    0.000000
19    0.000000
20    0.000000
21    0.000000
22    0.000000
23    0.000000
24         NaN
25    0.000000
26    0.000000
27         NaN
28    0.000000
29         NaN
30    0.003729

In [ ]:
print(processed_nix_inspect_df.isna().sum())
processed_nix_inspect_df['average_bc'] = processed_nix_inspect_df['average_bc'].fillna(0)
print(processed_nix_inspect_df.isna().sum())

full_name              0
date                   0
stargazers_count       0
days_since_creation    0
average_bc             9
dtype: int64
full_name              0
date                   0
stargazers_count       0
days_since_creation    0
average_bc             0
dtype: int64

In [ ]:
processed_ore_miner_df = process_repo('tonyke-bot/ore-miner', miner_df_cleaned)
print(processed_ore_miner_df)

               full_name        date  stargazers_count  days_since_creation  \
0   tonyke-bot/ore-miner  2024-04-13                70                    0
1   tonyke-bot/ore-miner  2024-04-14               115                    1
2   tonyke-bot/ore-miner  2024-04-15                63                    2
3   tonyke-bot/ore-miner  2024-04-16               110                    3
4   tonyke-bot/ore-miner  2024-04-17                72                    4
5   tonyke-bot/ore-miner  2024-04-18                26                    5
6   tonyke-bot/ore-miner  2024-04-19                 7                    6
7   tonyke-bot/ore-miner  2024-04-20                 1                    7
8   tonyke-bot/ore-miner  2024-04-21                 1                    8
9   tonyke-bot/ore-miner  2024-04-22                 0                    9
10  tonyke-bot/ore-miner  2024-04-23                 2                   10
11  tonyke-bot/ore-miner  2024-04-24                 0                   11
12  tonyke-bot/ore-miner  2024-04-25                 0                   12
13  tonyke-bot/ore-miner  2024-04-26                 0                   13
14  tonyke-bot/ore-miner  2024-04-27                 0                   14
15  tonyke-bot/ore-miner  2024-04-28                 1                   15
16  tonyke-bot/ore-miner  2024-04-29                 0                   16
17  tonyke-bot/ore-miner  2024-05-30                 0                   17
18  tonyke-bot/ore-miner  2024-05-01                 0                   18
19  tonyke-bot/ore-miner  2024-05-02                 0                   19
20  tonyke-bot/ore-miner  2024-05-03                 0                   20
21  tonyke-bot/ore-miner  2024-05-04                 0                   21
22  tonyke-bot/ore-miner  2024-05-05                 2                   22
23  tonyke-bot/ore-miner  2024-05-06                 0                   23
24  tonyke-bot/ore-miner  2024-05-07                 1                   24
25  tonyke-bot/ore-miner  2024-05-08                 0                   25
26  tonyke-bot/ore-miner  2024-05-09                 0                   26
27  tonyke-bot/ore-miner  2024-05-10                 1                   27
28  tonyke-bot/ore-miner  2024-05-11                 0                   28
29  tonyke-bot/ore-miner  2024-05-12                 0                   29
30  tonyke-bot/ore-miner  2024-05-13                 0                   30

    average_bc
0     0.000214
1     0.000507
2     0.004556
3     0.000428
4     0.000907
5          NaN
6          NaN
7          NaN
8          NaN
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27         NaN
28         NaN
29         NaN
30         NaN

In [ ]:
print(processed_ore_miner_df.isna().sum())
processed_ore_miner_df['average_bc'] = processed_ore_miner_df['average_bc'].fillna(0)
print(processed_ore_miner_df.isna().sum())

full_name               0
date                    0
stargazers_count        0
days_since_creation     0
average_bc             26
dtype: int64
full_name              0
date                   0
stargazers_count       0
days_since_creation    0
average_bc             0
dtype: int64

In [ ]:
processed_good_training_language_df = process_repo('tsoding/good_training_language', good_df_cleaned)
print(processed_good_training_language_df)

                         full_name        date  stargazers_count  \
0   tsoding/good_training_language  2024-04-02                47
1   tsoding/good_training_language  2024-04-03                56
2   tsoding/good_training_language  2024-04-04                44
3   tsoding/good_training_language  2024-04-05                20
4   tsoding/good_training_language  2024-04-06                 8
5   tsoding/good_training_language  2024-04-07                10
6   tsoding/good_training_language  2024-04-08                 5
7   tsoding/good_training_language  2024-04-09                 3
8   tsoding/good_training_language  2024-04-10                 4
9   tsoding/good_training_language  2024-04-11                 3
10  tsoding/good_training_language  2024-04-12                 2
11  tsoding/good_training_language  2024-04-13                 4
12  tsoding/good_training_language  2024-04-14                 4
13  tsoding/good_training_language  2024-04-15                 4
14  tsoding/good_training_language  2024-04-16                 4
15  tsoding/good_training_language  2024-04-17                 9
16  tsoding/good_training_language  2024-04-18                 3
17  tsoding/good_training_language  2024-04-19                 5
18  tsoding/good_training_language  2024-04-20                 7
19  tsoding/good_training_language  2024-04-21                 3
20  tsoding/good_training_language  2024-04-22                 1
21  tsoding/good_training_language  2024-04-23                 2
22  tsoding/good_training_language  2024-04-24                 4
23  tsoding/good_training_language  2024-04-25                 3
24  tsoding/good_training_language  2024-04-26                 2
25  tsoding/good_training_language  2024-04-27                 1
26  tsoding/good_training_language  2024-04-28                 2
27  tsoding/good_training_language  2024-04-29                 1
28  tsoding/good_training_language  2024-04-30                 3
29  tsoding/good_training_language  2024-05-01                 1
30  tsoding/good_training_language  2024-05-02                 5

    days_since_creation  average_bc
0                     0    0.000146
1                     1    0.000310
2                     2    0.000156
3                     3    0.000327
4                     4    0.000000
5                     5    0.000524
6                     6    0.019148
7                     7    0.000000
8                     8    0.013411
9                     9    0.000000
10                   10    0.000000
11                   11    0.000000
12                   12    0.004928
13                   13    0.000000
14                   14    0.000000
15                   15    0.000000
16                   16    0.000000
17                   17    0.000000
18                   18    0.001327
19                   19    0.000000
20                   20    0.000000
21                   21    0.000000
22                   22    0.000000
23                   23    0.000000
24                   24    0.000000
25                   25    0.000000
26                   26    0.000000
27                   27    0.000000
28                   28    0.000000
29                   29    0.000000
30                   30    0.000000

In [ ]:
final_df = pd.concat([repo_df, processed_ore_cli_gpu_df, processed_nix_inspect_df, processed_ore_miner_df, processed_good_training_language_df], ignore_index=True)
print(final_df)

                          full_name        date  stargazers_count  \
0              AmrDeveloper/ClangQL  2024-04-05                 2
1              AmrDeveloper/ClangQL  2024-04-06                22
2              AmrDeveloper/ClangQL  2024-04-07                79
3              AmrDeveloper/ClangQL  2024-04-08               113
4              AmrDeveloper/ClangQL  2024-04-09                75
..                              ...         ...               ...
150  tsoding/good_training_language  2024-04-28                 2
151  tsoding/good_training_language  2024-04-29                 1
152  tsoding/good_training_language  2024-04-30                 3
153  tsoding/good_training_language  2024-05-01                 1
154  tsoding/good_training_language  2024-05-02                 5

     days_since_creation  average_bc
0                      0    0.000000
1                      1    0.001326
2                      2    0.001998
3                      3    0.000545
4                      4    0.002579
..                   ...         ...
150                   26    0.000000
151                   27    0.000000
152                   28    0.000000
153                   29    0.000000
154                   30    0.000000

[155 rows x 5 columns]

In [ ]:
print(final_df.isna().sum())

full_name              0
date                   0
stargazers_count       0
days_since_creation    0
average_bc             0
dtype: int64

In [ ]:
repo_df.to_csv('/content/drive/MyDrive/PMF 2 4/STROJNO + MREÅ½E/Projekt_v2/ClangQL_for_LSTM.csv', index=False)
processed_ore_cli_gpu_df.to_csv('/content/drive/MyDrive/PMF 2 4/STROJNO + MREÅ½E/Projekt_v2/ore_cli_gpu_for_LSTM.csv', index=False)
processed_nix_inspect_df.to_csv('/content/drive/MyDrive/PMF 2 4/STROJNO + MREÅ½E/Projekt_v2/nix_inspect_for_LSTM.csv', index=False)
processed_ore_miner_df.to_csv('/content/drive/MyDrive/PMF 2 4/STROJNO + MREÅ½E/Projekt_v2/ore_miner_for_LSTM.csv', index=False)
processed_good_training_language_df.to_csv('/content/drive/MyDrive/PMF 2 4/STROJNO + MREÅ½E/Projekt_v2/good_training_language_for_LSTM.csv', index=False)

final_df.to_csv('/content/drive/MyDrive/PMF 2 4/STROJNO + MREÅ½E/Projekt_v2/final_for_LSTM.csv', index=False)